export const ROAST_DATA = {

  pauseTexts: [
    "you paused like the game personally embarrassed you and you needed a moment to emotionally recover.",
    "that pause looks less like strategy and more like your confidence packing its bags and leaving.",
    "you really froze mid-game like your brain saw what was coming and tried to escape.",
    "this pause feels like your hands needed therapy after that gameplay.",
    "you didn’t pause the game, the game paused you out of pure disappointment.",
    "that’s the kind of pause you make when your soul has officially disconnected from your fingers.",
    "you hit pause like the game just read you out loud and you couldn’t handle it.",
    "this is not a tactical pause, this is emotional buffering.",
    "that pause smells like regret and lost potential.",
    "you’re standing still like your confidence just blue-screened.",
    "the way you paused, it’s giving 'i've already lost but i'm pretending.'",
    "you froze so hard even the game knew something went wrong.",
    "this pause feels like your nervous system rage-quit before your hands did.",
    "you stopped moving like your brain just realized it wasn’t built for this.",
    "that pause wasn’t planned, it was survival instinct.",
    "you paused like the controller personally betrayed you.",
    "this is the type of pause people do when their ego needs a safe space.",
    "your hands paused because your pride couldn’t continue.",
    "that pause has the energy of someone googling 'how to be better instantly.'",
    "this is not a break, this is avoidance.",
    "you didn’t pause to think, you paused to cope.",
    "this pause feels like your last two braincells are fighting for control.",
    "you froze out of nowhere like your skill subscription just expired.",
    "this isn’t a pause, this is a midgame identity crisis.",
    "you paused because your expectations were higher than your ability.",
    "that pause looks like panic wearing a headset.",
    "you paused like the tutorial lied to you.",
    "this pause screams 'i thought i was better than this.'",
    "you stopped like your entire build was emotional damage.",
    "that pause wasn’t for strategy, it was to grieve.",
    "you paused because your confidence pulled a disappearing act.",
    "the game is still running but you mentally are not.",
    "this pause smells like someone rethinking life choices.",
    "you froze exactly like someone who didn’t expect to lose this badly.",
    "you paused like your inner voice finally caught up.",
    "this is what happens when ego meets reality.",
    "that pause is louder than your entire gameplay.",
    "you stopped moving like hope just left the building.",
    "you paused because the truth hit you mid-match.",
    "that pause is your brain filing a missing person report for your talent.",
    "this is not lag, this is psychological damage.",
    "the way you froze says more than your score ever could.",
    "this pause feels like embarrassment in slow motion.",
    "you didn’t pause out of choice, your soul hit the brakes.",
    "this pause looks like you lost the argument between confidence and skill.",
    "you froze like you just realized you’ve been carried your whole life.",
    "this pause is sponsored by disappointment.",
    "you paused because your expectations just lost a fight with reality.",
    "your character stopped moving before your pride did.",
    "this pause feels like defeat wearing headphones.",
    "you froze because the game exposed you."
  ],

  disconnectTexts: [
    "your hand disappeared like it didn't want to be associated with that performance anymore.",
    "even your hand had enough of what you were doing.",
    "the tracking lost your hand but your gameplay already lost the match.",
    "your hand exited the session out of self-respect.",
    "your camera couldn't handle the secondhand embarrassment.",
    "your hand left like it didn't sign up for this disaster.",
    "even your setup is trying to escape you.",
    "your tech said 'i’m not built for this type of nonsense.'",
    "your hand faded out like it didn’t want its name attached to this.",
    "the camera didn’t lose you — it disowned you.",
    "your hand rage-quit faster than your brain could.",
    "your hardware is distancing itself from your decisions.",
    "your hand went invisible out of pure embarrassment.",
    "the tracker looked at this performance and chose peace.",
    "your rig saw what you were doing and filed for divorce.",
    "your camera pretended you weren’t there out of respect for itself.",
    "your hand disconnected spiritually before it did digitally.",
    "even your equipment is trying to protect itself from you.",
    "your hand vanished like your win chance.",
    "your gear is practicing self-care by avoiding you.",
    "your camera couldn’t handle the pressure of pretending this was okay.",
    "your hand walked out mid-scene like a disappointed actor.",
    "your setup is having an identity crisis because of you.",
    "the sensor gave up hope before the game did.",
    "your hand left the session and took your dignity with it.",
    "the tracking system is officially done defending you.",
    "your rig is judging you and honestly… fair.",
    "your hardware is trying to save face by not showing you anymore.",
    "your hand went missing like your winning strategy.",
    "your camera couldn't keep lying anymore.",
    "your setup just blinked in disbelief.",
    "your hand faded like your confidence.",
    "even your tech is tired of carrying you.",
    "your hand ghosted because it knows a bad situation when it sees one.",
    "your gear refuses to be an accessory to this.",
    "your camera had to look away.",
    "your tracker officially lost faith.",
    "your equipment is emotionally exhausted.",
    "your hand took the emergency exit.",
    "your setup is pretending you’re not home.",
    "technically your hand left, spiritually you’ve been gone.",
    "your rig couldn’t continue watching this unfold.",
    "your hand evacuation was instant.",
    "your camera noped out in silence.",
    "your hand exited like it had a better future elsewhere.",
    "even your shadows don’t want to follow you now.",
    "the input system said 'nope.'",
    "your hardware chose dignity.",
    "the tracker isn’t broken, it just refuses.",
    "even your camera has standards."
  ],

  middleFingerTexts: [
    "that gesture has more confidence than your entire gameplay history.",
    "you point that finger like it’s going to fix what just happened.",
    "that finger working overtime to cover for your performance.",
    "you really thought that would carry you.",
    "doing that after playing like that is wild.",
    "you’re throwing hands, but not landing talent.",
    "your confidence is ahead of your skill by several updates.",
    "you just threatened the screen instead of improving.",
    "that gesture is louder than your actual ability.",
    "you look mad at everything except the real problem.",
    "you flexed like your gameplay earned it.",
    "that finger doing more work than your strategy ever did.",
    "you mad at the game like it wronged you personally.",
    "throwing attitude instead of accuracy.",
    "your aim missed but your ego didn’t.",
    "you showed the finger instead of showing improvement.",
    "you really thought that would scare the pixels.",
    "all that emotion, zero execution.",
    "you brought rage to a skill fight.",
    "you acting legendary after playing like a tutorial example.",
    "that finger just self-reported your frustration.",
    "you really said 'anger > practice.'",
    "emotional output higher than skill input.",
    "you flipping off your own potential at this point.",
    "you flexed but forgot to perform.",
    "that gesture costs more energy than your entire playstyle.",
    "you mad loud for someone that quiet in results.",
    "you pointing like you’re innocent.",
    "that move screamed 'i thought i'd win.'",
    "you showed attitude where you should’ve shown growth.",
    "your rage has better form than your gameplay.",
    "you tried to intimidate the game instead of learning it.",
    "wild confidence for such mild output.",
    "you pressed rage instead of retry.",
    "you mad at pixels like they owe you.",
    "you fighting the screen instead of your mistakes.",
    "your ego stayed online when your skills left.",
    "that finger aimed better than you did.",
    "you flexed your fingers instead of your ability.",
    "you really expected applause for that?",
    "acting dangerous after playing harmless.",
    "you loud where you should be precise.",
    "that gesture has way too much faith behind it.",
    "all ego, no results.",
    "you shook the air, not the leaderboard.",
    "you throwing shade at the wrong target.",
    "you tried intimidation when you needed improvement.",
    "you showed the finger instead of showing progress.",
    "your confidence is allergic to reality.",
    "that move blamed everything except you.",
    "angry energy, beginner output.",
    "you went dramatic instead of getting better."
  ]

};